# Generated by Django 6.1.1 on 2026-10-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
