from django.urls import path
from . import views

urlpatterns=[
    path("",views.home,name="home"),
    path("dashboard/",views.dashboard,name="dashboard"),
    path("api/dashboard/",views.dashboard_api,name="dashboard_api"),
    path("profile/edit/",views.edit_profile,name="edit_profile"),
    path("api/profile/edit/", views.edit_profile_api, name="edit_profile_api"),
    path("api/account/username/",views.change_username_api,name="change_username_api"),
    path("api/account/password/", views.change_password_api,name="change_password_api"),
    path("upload/",views.upload_video,name="upload_video"),
    path("api/videos/upload/",views.upload_video_api,name="upload_video_api"),
    path("api/categories/",views.category_list_api,name="category_list_api"),
    path("register/",views.register,name="register"),
    path("login/",views.login,name="login"),
    path("api/login/",views.login_api,name="login_api"),
    path("api/register/",views.register_api,name="register_api"),
    path("api/videos/",views.video_list_api,name="video_list_api"),
    path("api/videos/trending/",views.trending_videos_api,name="trending_videos_api"),
    path("api/videos/<int:video_id>/",views.video_detail_api,name="video_detail_api"),
    path("api/videos/<int:video_id>/view/",views.increment_view_count,name="increment_view_count"),
    path("api/me/",views.current_user,name="current_user"),
    path("api/users/<int:user_id>/",views.user_profile_api,name="user_profile_api"),
    path("api/users/<int:user_id>/videos/",views.user_videos_api,name="user_videos_api"),
    path("api/users/<int:user_id>/subscribe/",views.toggle_subscription_api,name="toggle_subscription_api"),
    path("logout/",views.logout_view,name="logout"),
    path("<int:video_id>/react/",views.react_to_video,name="react_to_video"),
    path("<int:video_id>/comments/",views.comments,name="comments"),
    path("<int:video_id>/edit/",views.edit_video,name="edit_video"),
    path("api/videos/<int:video_id>/edit/",views.edit_video_api,name="edit_video_api"),
    path("<int:video_id>/delete/",views.delete_video,name="delete_video"),
    path("api/videos/<int:video_id>/delete/",views.delete_video_api,name="delete_video_api"),
    path("user/<int:user_id>/",views.user_profile,name="user_profile"),
    path("user/<int:user_id>/subscribe/",views.toggle_subscription,name="toggle_subscription"),
    path("<int:video_id>/",views.video_detail,name="video_detail"),
]